In [28]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F 
import math 

In [87]:
X = torch.Tensor([[0, 1, 3, 5, 4], 
                  [2, 4, 8, 7, 6], 
                  [7, 3, 8, 9, 2]]) # Input embedding 
X = X.float()
X = X.unsqueeze(0)
print(X)
X.shape

tensor([[[0., 1., 3., 5., 4.],
         [2., 4., 8., 7., 6.],
         [7., 3., 8., 9., 2.]]])


torch.Size([1, 3, 5])

In [88]:
wQ = nn.Linear(5, 5)
wK = nn.Linear(5, 5) 
wV = nn.Linear(5, 5) 

In [89]:
Q = wQ(X) 
K = wK(X) 
V = wV(X) 

In [90]:
print(Q)

tensor([[[-1.6948, -0.3403,  1.4904, -0.4585, -1.4751],
         [-2.4711, -0.1693,  3.3973, -0.6491, -3.0588],
         [-1.0059,  2.9428,  1.8205, -1.1039, -2.7945]]],
       grad_fn=<ViewBackward0>)


In [91]:
print(type(K))

<class 'torch.Tensor'>


In [92]:
print(V)

tensor([[[ 1.0895,  1.1473,  4.4954,  0.0751,  3.7503],
         [-0.0841,  2.2096,  7.6315, -0.2643,  8.0407],
         [-1.1319,  4.1929,  5.2567, -3.2167,  9.2039]]],
       grad_fn=<ViewBackward0>)


# Scaled Dot Product Attention

In [93]:
dk = K.size(-1)
print(dk)

5


In [94]:
K.size()

torch.Size([1, 3, 5])

In [98]:
scores = torch.matmul(Q, K.transpose(-1, -2)) / math.sqrt(dk)
print(scores)

tensor([[[ 5.3933,  9.3230,  8.6391],
         [10.2612, 17.8486, 15.6759],
         [ 5.3080,  8.0303,  1.6710]]], grad_fn=<DivBackward0>)


In [96]:
sm_scores = F.softmax(scores, dim=1)
print(sm_scores)

tensor([[[7.5778e-03, 1.9826e-04, 8.7816e-04],
         [9.8546e-01, 9.9975e-01, 9.9912e-01],
         [6.9579e-03, 5.4428e-05, 8.2679e-07]]], grad_fn=<SoftmaxBackward0>)


In [99]:
attention = torch.matmul(sm_scores, V)
print(attention)

tensor([[[ 7.2456e-03,  1.2814e-02,  4.0195e-02, -2.3079e-03,  3.8096e-02],
         [-1.4126e-01,  7.5289e+00,  1.7312e+01, -3.4041e+00,  2.0930e+01],
         [ 7.5754e-03,  8.1063e-03,  3.1698e-02,  5.0564e-04,  2.6539e-02]]],
       grad_fn=<UnsafeViewBackward0>)


# Multi-head Attention  
num_heads = 2 

In [103]:
K.shape[1]

3

In [ ]:
new_dk = 

In [102]:
multi_attention = torch.con

torch.Size([1, 3, 5])